apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.apiName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "platform.apiName" . }}
rules:

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "delete"]


  - apiGroups: [""]
    resources: ["resourcequotas", "limitranges", "secrets"]
    verbs: ["get", "create", "patch", "update"]


  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "create", "patch", "update"]


  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]


  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get", "list", "create", "patch", "update"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames: ["admin"]
    verbs: ["bind"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "platform.apiName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "platform.apiName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "platform.apiName" . }}
    namespace: {{ .Release.Namespace }}
